### ISSUE TITLE
I'd like to work on this project.

### ISSUE THREAD

**Issue by vadymrass** [Clm-Roig/decibel-agenda#1]
Hello Grottocenter!
Hope you are doing well.

I am Vadym Rassynskyi from Ukraine and I have more than 5+ years of experience in web development.
I am very familiar with React, Next.js, MUI, Node.js, Express, MongoDB and other relevant skills.
I think your project idea is great so I'd like to contribute to this project.
Now I am free, so I can work for you full-time.
Please feel free to contact me anytime.

Regards,
Vadym.

**Comment by Clm-Roig** [comment]
Hey, thanks for your message. I'm sorry but I'm not interested in working with someone else on this project.

Also, be careful with your automated script: you have used one of my organizations name ("Grottocenter") which is not related whatsoever to this repository 😅 

Have a good day!
